SELECT * FROM SYSTEM_USER;

SELECT * FROM SYSTEM_ROLE;

SELECT * FROM SYSTEM_RESOURCES;

SELECT * FROM SYSTEM_USER_ROLE;

SELECT * FROM SYSTEM_ROLE_RESOURCE;

SELECT * FROM SYSTEM_RESOURCES R;

SELECT R.* FROM SYSTEM_RESOURCES R,SYSTEM_ROLE_RESOURCE T
WHERE R.ID=T.SYSTEM_RESOURCE_ID
AND T.SYSTEM_ROLE_ID=1;

SELECT R2.* FROM SYSTEM_RESOURCES R1 LEFT JOIN  SYSTEM_RESOURCES R2 ON R2.PARENT_ID=R1.ID WHERE R1.ID=1;


SELECT T2.* 
FROM SYSTEM_RESOURCES AS T1
LEFT JOIN SYSTEM_RESOURCES AS T2 ON T2.PARENT_ID = T1.ID
WHERE T1.ID= 1;


/**查询没有和角色关联的权限URL**/
SELECT * FROM SYSTEM_RESOURCES WHERE ID NOT IN (SELECT DISTINCT SYSTEM_RESOURCE_ID FROM SYSTEM_ROLE_RESOURCE);